name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: DB-tests
      run: cargo test -- --nocapture

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: DB-FMT
      run: cargo fmt -- --check


  build_db:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: WQL-install-clippy
      run: rustup component add clippy
    - name: WQL-clippy
      run: cargo clippy -- -W clippy::pedantic

